using System.Collections.Generic;
using System.IO;
using System.Reflection;
using AutopilotMonitor.Shared.Models;
using Newtonsoft.Json;

namespace AutopilotMonitor.Functions.Services
{
    /// <summary>
    /// Built-in analyze rules loaded from embedded JSON resource.
    /// The JSON is generated by the CI combine script from individual rule files in rules/analyze/.
    /// </summary>
    public static class BuiltInAnalyzeRules
    {
        public static List<AnalyzeRule> GetAll()
        {
            var assembly = Assembly.GetExecutingAssembly();
            using var stream = assembly.GetManifestResourceStream(
                "AutopilotMonitor.Functions.Rules.analyze-rules.json");
            using var reader = new StreamReader(stream!);
            var json = reader.ReadToEnd();
            var wrapper = JsonConvert.DeserializeObject<RulesWrapper<AnalyzeRule>>(json);
            var rules = wrapper?.Rules ?? new List<AnalyzeRule>();

            foreach (var rule in rules)
            {
                rule.IsBuiltIn = true;
            }

            return rules;
        }
    }
}
